default_language_version:
  python: python3.8
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: trailing-whitespace
  - repo: https://github.com/ecugol/pre-commit-hooks-django
    rev: v0.3.0
    hooks:
      - id: check-untracked-migrations
      - id: check-unapplied-migrations
  - repo: local
    hooks:
      - id: check
        name: Django check
        entry: python manage.py check
        language: system
        types: [python]
        always_run: true
      - id: test
        name: Django tests
        entry: python manage.py test
        language: system
        types: [python]
        always_run: true
