# Generated by Django 3.1.4 on 2021-01-02 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jtapi', '0002_auto_20200705_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='jamsession',
            name='is_unlisted',
            field=models.BooleanField(default=False),
        ),
    ]
