# Generated by Django 3.2.5 on 2021-07-29 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jtapi', '0003_jamsession_is_unlisted'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=2000)),
                ('site_url', models.URLField()),
            ],
        ),
    ]
