# Generated by Django 3.2.5 on 2021-07-30 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jtapi', '0004_songprovider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=100)),
                ('composer', models.CharField(max_length=200)),
                ('arranger', models.CharField(max_length=200)),
                ('song_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='jtapi.songprovider')),
            ],
        ),
    ]
