# Generated by Django 3.2.5 on 2021-07-30 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jtapi', '0005_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='artist',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='song',
            name='arranger',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='song',
            name='composer',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='song',
            name='subtitle',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
