# Generated by Django 3.2.5 on 2021-09-04 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jtapi', '0006_auto_20210729_2059'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('part_type', models.CharField(choices=[('Instrument', 'Instrument'), ('Transposition', 'Transposition')], max_length=20)),
            ],
        ),
    ]
