# Generated by Django 3.2.5 on 2021-09-04 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jtapi', '0007_partdefinition'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='jtapi.partdefinition')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='jtapi.song')),
            ],
        ),
    ]
