# Generated by Django 3.2.5 on 2021-09-05 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jtapi', '0008_songpart'),
    ]

    operations = [
        migrations.AddField(
            model_name='songpart',
            name='full_file_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='songpart',
            name='reference_url',
            field=models.URLField(blank=True),
        ),
    ]
