# Generated by Django 3.2.5 on 2021-09-06 20:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jtapi', '0010_auto_20210905_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='JamSessionSong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_queued', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_played', models.DateTimeField(blank=True, null=True)),
                ('state', models.CharField(choices=[('Queued', 'Queued'), ('Canceled', 'Canceled'), ('Deferred', 'Deferred'), ('Played', 'Played')], default='Queued', max_length=10)),
                ('jam_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jtapi.jamsession')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jtapi.song')),
            ],
        ),
        migrations.AddField(
            model_name='jamsession',
            name='songs',
            field=models.ManyToManyField(related_name='_jtapi_jamsession_songs_+', through='jtapi.JamSessionSong', to='jtapi.Song'),
        ),
    ]
