# Generated by Django 3.2.5 on 2021-12-18 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jtapi', '0011_auto_20210906_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jamsession',
            name='songs',
        ),
        migrations.AlterField(
            model_name='jamsessionsong',
            name='jam_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='jtapi.jamsession'),
        ),
        migrations.AlterField(
            model_name='jamsessionsong',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='jtapi.song'),
        ),
    ]
