# Generated by Django 5.0.6 on 2024-06-11 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jtapi', '0012_auto_20211217_2248'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='jamsessionsong',
            order_with_respect_to='jam_session',
        ),
    ]
